// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: api/grpc/internal_ai.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntegrationService_ListBuilders_FullMethodName    = "/internalaicopilot.integration.v1.IntegrationService/ListBuilders"
	IntegrationService_Consult_FullMethodName         = "/internalaicopilot.integration.v1.IntegrationService/Consult"
	IntegrationService_ProfileConsult_FullMethodName  = "/internalaicopilot.integration.v1.IntegrationService/ProfileConsult"
	IntegrationService_LineTaskConsult_FullMethodName = "/internalaicopilot.integration.v1.IntegrationService/LineTaskConsult"
)

// IntegrationServiceClient is the client API for IntegrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegrationServiceClient interface {
	ListBuilders(ctx context.Context, in *ListBuildersRequest, opts ...grpc.CallOption) (*ListBuildersResponse, error)
	Consult(ctx context.Context, in *ConsultRequest, opts ...grpc.CallOption) (*ConsultResponse, error)
	ProfileConsult(ctx context.Context, in *ProfileConsultRequest, opts ...grpc.CallOption) (*ProfileConsultResponse, error)
	LineTaskConsult(ctx context.Context, in *LineTaskConsultRequest, opts ...grpc.CallOption) (*LineTaskConsultResponse, error)
}

type integrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationServiceClient(cc grpc.ClientConnInterface) IntegrationServiceClient {
	return &integrationServiceClient{cc}
}

func (c *integrationServiceClient) ListBuilders(ctx context.Context, in *ListBuildersRequest, opts ...grpc.CallOption) (*ListBuildersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuildersResponse)
	err := c.cc.Invoke(ctx, IntegrationService_ListBuilders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) Consult(ctx context.Context, in *ConsultRequest, opts ...grpc.CallOption) (*ConsultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultResponse)
	err := c.cc.Invoke(ctx, IntegrationService_Consult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) ProfileConsult(ctx context.Context, in *ProfileConsultRequest, opts ...grpc.CallOption) (*ProfileConsultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileConsultResponse)
	err := c.cc.Invoke(ctx, IntegrationService_ProfileConsult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) LineTaskConsult(ctx context.Context, in *LineTaskConsultRequest, opts ...grpc.CallOption) (*LineTaskConsultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LineTaskConsultResponse)
	err := c.cc.Invoke(ctx, IntegrationService_LineTaskConsult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationServiceServer is the server API for IntegrationService service.
// All implementations must embed UnimplementedIntegrationServiceServer
// for forward compatibility.
type IntegrationServiceServer interface {
	ListBuilders(context.Context, *ListBuildersRequest) (*ListBuildersResponse, error)
	Consult(context.Context, *ConsultRequest) (*ConsultResponse, error)
	ProfileConsult(context.Context, *ProfileConsultRequest) (*ProfileConsultResponse, error)
	LineTaskConsult(context.Context, *LineTaskConsultRequest) (*LineTaskConsultResponse, error)
	mustEmbedUnimplementedIntegrationServiceServer()
}

// UnimplementedIntegrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntegrationServiceServer struct{}

func (UnimplementedIntegrationServiceServer) ListBuilders(context.Context, *ListBuildersRequest) (*ListBuildersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuilders not implemented")
}
func (UnimplementedIntegrationServiceServer) Consult(context.Context, *ConsultRequest) (*ConsultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consult not implemented")
}
func (UnimplementedIntegrationServiceServer) ProfileConsult(context.Context, *ProfileConsultRequest) (*ProfileConsultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileConsult not implemented")
}
func (UnimplementedIntegrationServiceServer) LineTaskConsult(context.Context, *LineTaskConsultRequest) (*LineTaskConsultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LineTaskConsult not implemented")
}
func (UnimplementedIntegrationServiceServer) mustEmbedUnimplementedIntegrationServiceServer() {}
func (UnimplementedIntegrationServiceServer) testEmbeddedByValue()                            {}

// UnsafeIntegrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationServiceServer will
// result in compilation errors.
type UnsafeIntegrationServiceServer interface {
	mustEmbedUnimplementedIntegrationServiceServer()
}

func RegisterIntegrationServiceServer(s grpc.ServiceRegistrar, srv IntegrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedIntegrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntegrationService_ServiceDesc, srv)
}

func _IntegrationService_ListBuilders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuildersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).ListBuilders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_ListBuilders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).ListBuilders(ctx, req.(*ListBuildersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_Consult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).Consult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_Consult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).Consult(ctx, req.(*ConsultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_ProfileConsult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileConsultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).ProfileConsult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_ProfileConsult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).ProfileConsult(ctx, req.(*ProfileConsultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_LineTaskConsult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LineTaskConsultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).LineTaskConsult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_LineTaskConsult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).LineTaskConsult(ctx, req.(*LineTaskConsultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegrationService_ServiceDesc is the grpc.ServiceDesc for IntegrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntegrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalaicopilot.integration.v1.IntegrationService",
	HandlerType: (*IntegrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBuilders",
			Handler:    _IntegrationService_ListBuilders_Handler,
		},
		{
			MethodName: "Consult",
			Handler:    _IntegrationService_Consult_Handler,
		},
		{
			MethodName: "ProfileConsult",
			Handler:    _IntegrationService_ProfileConsult_Handler,
		},
		{
			MethodName: "LineTaskConsult",
			Handler:    _IntegrationService_LineTaskConsult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/internal_ai.proto",
}
