// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/grpc/internal_ai.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBuildersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildersRequest) Reset() {
	*x = ListBuildersRequest{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildersRequest) ProtoMessage() {}

func (x *ListBuildersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildersRequest.ProtoReflect.Descriptor instead.
func (*ListBuildersRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ListBuildersRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ListBuildersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builders      []*BuilderSummary      `protobuf:"bytes,1,rep,name=builders,proto3" json:"builders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildersResponse) Reset() {
	*x = ListBuildersResponse{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildersResponse) ProtoMessage() {}

func (x *ListBuildersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildersResponse.ProtoReflect.Descriptor instead.
func (*ListBuildersResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ListBuildersResponse) GetBuilders() []*BuilderSummary {
	if x != nil {
		return x.Builders
	}
	return nil
}

type BuilderSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BuilderId           int32                  `protobuf:"varint,1,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	BuilderCode         string                 `protobuf:"bytes,2,opt,name=builder_code,json=builderCode,proto3" json:"builder_code,omitempty"`
	GroupKey            *string                `protobuf:"bytes,3,opt,name=group_key,json=groupKey,proto3,oneof" json:"group_key,omitempty"`
	GroupLabel          string                 `protobuf:"bytes,4,opt,name=group_label,json=groupLabel,proto3" json:"group_label,omitempty"`
	Name                string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	IncludeFile         bool                   `protobuf:"varint,7,opt,name=include_file,json=includeFile,proto3" json:"include_file,omitempty"`
	DefaultOutputFormat *string                `protobuf:"bytes,8,opt,name=default_output_format,json=defaultOutputFormat,proto3,oneof" json:"default_output_format,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BuilderSummary) Reset() {
	*x = BuilderSummary{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuilderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuilderSummary) ProtoMessage() {}

func (x *BuilderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuilderSummary.ProtoReflect.Descriptor instead.
func (*BuilderSummary) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{2}
}

func (x *BuilderSummary) GetBuilderId() int32 {
	if x != nil {
		return x.BuilderId
	}
	return 0
}

func (x *BuilderSummary) GetBuilderCode() string {
	if x != nil {
		return x.BuilderCode
	}
	return ""
}

func (x *BuilderSummary) GetGroupKey() string {
	if x != nil && x.GroupKey != nil {
		return *x.GroupKey
	}
	return ""
}

func (x *BuilderSummary) GetGroupLabel() string {
	if x != nil {
		return x.GroupLabel
	}
	return ""
}

func (x *BuilderSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuilderSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BuilderSummary) GetIncludeFile() bool {
	if x != nil {
		return x.IncludeFile
	}
	return false
}

func (x *BuilderSummary) GetDefaultOutputFormat() string {
	if x != nil && x.DefaultOutputFormat != nil {
		return *x.DefaultOutputFormat
	}
	return ""
}

type ConsultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BuilderId     int32                  `protobuf:"varint,2,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ClientIp      string                 `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultRequest) Reset() {
	*x = ConsultRequest{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultRequest) ProtoMessage() {}

func (x *ConsultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultRequest.ProtoReflect.Descriptor instead.
func (*ConsultRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ConsultRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ConsultRequest) GetBuilderId() int32 {
	if x != nil {
		return x.BuilderId
	}
	return 0
}

func (x *ConsultRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ConsultRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *ConsultRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ConsultRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{4}
}

func (x *Attachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConsultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusAns     string                 `protobuf:"bytes,2,opt,name=status_ans,json=statusAns,proto3" json:"status_ans,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	File          *FilePayload           `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultResponse) Reset() {
	*x = ConsultResponse{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultResponse) ProtoMessage() {}

func (x *ConsultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultResponse.ProtoReflect.Descriptor instead.
func (*ConsultResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{5}
}

func (x *ConsultResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ConsultResponse) GetStatusAns() string {
	if x != nil {
		return x.StatusAns
	}
	return ""
}

func (x *ConsultResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ConsultResponse) GetFile() *FilePayload {
	if x != nil {
		return x.File
	}
	return nil
}

type ProfileConsultRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BuilderId      int32                  `protobuf:"varint,2,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	SubjectProfile *SubjectProfile        `protobuf:"bytes,4,opt,name=subject_profile,json=subjectProfile,proto3" json:"subject_profile,omitempty"`
	Text           string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	ClientIp       string                 `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserText       string                 `protobuf:"bytes,7,opt,name=user_text,json=userText,proto3" json:"user_text,omitempty"`
	IntentText     string                 `protobuf:"bytes,8,opt,name=intent_text,json=intentText,proto3" json:"intent_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileConsultRequest) Reset() {
	*x = ProfileConsultRequest{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileConsultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileConsultRequest) ProtoMessage() {}

func (x *ProfileConsultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileConsultRequest.ProtoReflect.Descriptor instead.
func (*ProfileConsultRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileConsultRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ProfileConsultRequest) GetBuilderId() int32 {
	if x != nil {
		return x.BuilderId
	}
	return 0
}

func (x *ProfileConsultRequest) GetSubjectProfile() *SubjectProfile {
	if x != nil {
		return x.SubjectProfile
	}
	return nil
}

func (x *ProfileConsultRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ProfileConsultRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ProfileConsultRequest) GetUserText() string {
	if x != nil {
		return x.UserText
	}
	return ""
}

func (x *ProfileConsultRequest) GetIntentText() string {
	if x != nil {
		return x.IntentText
	}
	return ""
}

type SubjectProfile struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SubjectId        string                    `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	AnalysisPayloads []*SubjectAnalysisPayload `protobuf:"bytes,2,rep,name=analysis_payloads,json=analysisPayloads,proto3" json:"analysis_payloads,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubjectProfile) Reset() {
	*x = SubjectProfile{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectProfile) ProtoMessage() {}

func (x *SubjectProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectProfile.ProtoReflect.Descriptor instead.
func (*SubjectProfile) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{7}
}

func (x *SubjectProfile) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SubjectProfile) GetAnalysisPayloads() []*SubjectAnalysisPayload {
	if x != nil {
		return x.AnalysisPayloads
	}
	return nil
}

type SubjectAnalysisPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisType  string                 `protobuf:"bytes,1,opt,name=analysis_type,json=analysisType,proto3" json:"analysis_type,omitempty"`
	TheoryVersion *string                `protobuf:"bytes,2,opt,name=theory_version,json=theoryVersion,proto3,oneof" json:"theory_version,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectAnalysisPayload) Reset() {
	*x = SubjectAnalysisPayload{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectAnalysisPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectAnalysisPayload) ProtoMessage() {}

func (x *SubjectAnalysisPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectAnalysisPayload.ProtoReflect.Descriptor instead.
func (*SubjectAnalysisPayload) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{8}
}

func (x *SubjectAnalysisPayload) GetAnalysisType() string {
	if x != nil {
		return x.AnalysisType
	}
	return ""
}

func (x *SubjectAnalysisPayload) GetTheoryVersion() string {
	if x != nil && x.TheoryVersion != nil {
		return *x.TheoryVersion
	}
	return ""
}

func (x *SubjectAnalysisPayload) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ProfileConsultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusAns     string                 `protobuf:"bytes,2,opt,name=status_ans,json=statusAns,proto3" json:"status_ans,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileConsultResponse) Reset() {
	*x = ProfileConsultResponse{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileConsultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileConsultResponse) ProtoMessage() {}

func (x *ProfileConsultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileConsultResponse.ProtoReflect.Descriptor instead.
func (*ProfileConsultResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{9}
}

func (x *ProfileConsultResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ProfileConsultResponse) GetStatusAns() string {
	if x != nil {
		return x.StatusAns
	}
	return ""
}

func (x *ProfileConsultResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type LineTaskConsultRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppId              string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BuilderId          int32                  `protobuf:"varint,2,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	MessageText        string                 `protobuf:"bytes,3,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	ReferenceTime      string                 `protobuf:"bytes,4,opt,name=reference_time,json=referenceTime,proto3" json:"reference_time,omitempty"`
	TimeZone           string                 `protobuf:"bytes,5,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	ClientIp           string                 `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	SupportedTaskTypes []string               `protobuf:"bytes,7,rep,name=supported_task_types,json=supportedTaskTypes,proto3" json:"supported_task_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LineTaskConsultRequest) Reset() {
	*x = LineTaskConsultRequest{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineTaskConsultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineTaskConsultRequest) ProtoMessage() {}

func (x *LineTaskConsultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineTaskConsultRequest.ProtoReflect.Descriptor instead.
func (*LineTaskConsultRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{10}
}

func (x *LineTaskConsultRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *LineTaskConsultRequest) GetBuilderId() int32 {
	if x != nil {
		return x.BuilderId
	}
	return 0
}

func (x *LineTaskConsultRequest) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *LineTaskConsultRequest) GetReferenceTime() string {
	if x != nil {
		return x.ReferenceTime
	}
	return ""
}

func (x *LineTaskConsultRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *LineTaskConsultRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LineTaskConsultRequest) GetSupportedTaskTypes() []string {
	if x != nil {
		return x.SupportedTaskTypes
	}
	return nil
}

type LineTaskConsultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	StartAt       string                 `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         string                 `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	MissingFields []string               `protobuf:"bytes,6,rep,name=missing_fields,json=missingFields,proto3" json:"missing_fields,omitempty"`
	TaskType      string                 `protobuf:"bytes,7,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineTaskConsultResponse) Reset() {
	*x = LineTaskConsultResponse{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineTaskConsultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineTaskConsultResponse) ProtoMessage() {}

func (x *LineTaskConsultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineTaskConsultResponse.ProtoReflect.Descriptor instead.
func (*LineTaskConsultResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{11}
}

func (x *LineTaskConsultResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LineTaskConsultResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *LineTaskConsultResponse) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *LineTaskConsultResponse) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *LineTaskConsultResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *LineTaskConsultResponse) GetMissingFields() []string {
	if x != nil {
		return x.MissingFields
	}
	return nil
}

func (x *LineTaskConsultResponse) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type FilePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePayload) Reset() {
	*x = FilePayload{}
	mi := &file_api_grpc_internal_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePayload) ProtoMessage() {}

func (x *FilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_internal_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePayload.ProtoReflect.Descriptor instead.
func (*FilePayload) Descriptor() ([]byte, []int) {
	return file_api_grpc_internal_ai_proto_rawDescGZIP(), []int{12}
}

func (x *FilePayload) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FilePayload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FilePayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_grpc_internal_ai_proto protoreflect.FileDescriptor

const file_api_grpc_internal_ai_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/grpc/internal_ai.proto\x12 internalaicopilot.integration.v1\x1a\x1cgoogle/protobuf/struct.proto\",\n" +
	"\x13ListBuildersRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"d\n" +
	"\x14ListBuildersResponse\x12L\n" +
	"\bbuilders\x18\x01 \x03(\v20.internalaicopilot.integration.v1.BuilderSummaryR\bbuilders\"\xcf\x02\n" +
	"\x0eBuilderSummary\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x01 \x01(\x05R\tbuilderId\x12!\n" +
	"\fbuilder_code\x18\x02 \x01(\tR\vbuilderCode\x12 \n" +
	"\tgroup_key\x18\x03 \x01(\tH\x00R\bgroupKey\x88\x01\x01\x12\x1f\n" +
	"\vgroup_label\x18\x04 \x01(\tR\n" +
	"groupLabel\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12!\n" +
	"\finclude_file\x18\a \x01(\bR\vincludeFile\x127\n" +
	"\x15default_output_format\x18\b \x01(\tH\x01R\x13defaultOutputFormat\x88\x01\x01B\f\n" +
	"\n" +
	"_group_keyB\x18\n" +
	"\x16_default_output_format\"\xec\x01\n" +
	"\x0eConsultRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x02 \x01(\x05R\tbuilderId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\x12N\n" +
	"\vattachments\x18\x05 \x03(\v2,.internalaicopilot.integration.v1.AttachmentR\vattachments\x12\x1b\n" +
	"\tclient_ip\x18\x06 \x01(\tR\bclientIp\"`\n" +
	"\n" +
	"Attachment\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xa7\x01\n" +
	"\x0fConsultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1d\n" +
	"\n" +
	"status_ans\x18\x02 \x01(\tR\tstatusAns\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x12A\n" +
	"\x04file\x18\x04 \x01(\v2-.internalaicopilot.integration.v1.FilePayloadR\x04file\"\x97\x02\n" +
	"\x15ProfileConsultRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x02 \x01(\x05R\tbuilderId\x12Y\n" +
	"\x0fsubject_profile\x18\x04 \x01(\v20.internalaicopilot.integration.v1.SubjectProfileR\x0esubjectProfile\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1b\n" +
	"\tclient_ip\x18\x06 \x01(\tR\bclientIp\x12\x1b\n" +
	"\tuser_text\x18\a \x01(\tR\buserText\x12\x1f\n" +
	"\vintent_text\x18\b \x01(\tR\n" +
	"intentText\"\x96\x01\n" +
	"\x0eSubjectProfile\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12e\n" +
	"\x11analysis_payloads\x18\x02 \x03(\v28.internalaicopilot.integration.v1.SubjectAnalysisPayloadR\x10analysisPayloads\"\xaf\x01\n" +
	"\x16SubjectAnalysisPayload\x12#\n" +
	"\ranalysis_type\x18\x01 \x01(\tR\fanalysisType\x12*\n" +
	"\x0etheory_version\x18\x02 \x01(\tH\x00R\rtheoryVersion\x88\x01\x01\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayloadB\x11\n" +
	"\x0f_theory_version\"k\n" +
	"\x16ProfileConsultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1d\n" +
	"\n" +
	"status_ans\x18\x02 \x01(\tR\tstatusAns\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\"\x84\x02\n" +
	"\x16LineTaskConsultRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x02 \x01(\x05R\tbuilderId\x12!\n" +
	"\fmessage_text\x18\x03 \x01(\tR\vmessageText\x12%\n" +
	"\x0ereference_time\x18\x04 \x01(\tR\rreferenceTime\x12\x1b\n" +
	"\ttime_zone\x18\x05 \x01(\tR\btimeZone\x12\x1b\n" +
	"\tclient_ip\x18\x06 \x01(\tR\bclientIp\x120\n" +
	"\x14supported_task_types\x18\a \x03(\tR\x12supportedTaskTypes\"\xe3\x01\n" +
	"\x17LineTaskConsultResponse\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x19\n" +
	"\bstart_at\x18\x03 \x01(\tR\astartAt\x12\x15\n" +
	"\x06end_at\x18\x04 \x01(\tR\x05endAt\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12%\n" +
	"\x0emissing_fields\x18\x06 \x03(\tR\rmissingFields\x12\x1b\n" +
	"\ttask_type\x18\a \x01(\tR\btaskType\"a\n" +
	"\vFilePayload\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data2\x92\x04\n" +
	"\x12IntegrationService\x12}\n" +
	"\fListBuilders\x125.internalaicopilot.integration.v1.ListBuildersRequest\x1a6.internalaicopilot.integration.v1.ListBuildersResponse\x12n\n" +
	"\aConsult\x120.internalaicopilot.integration.v1.ConsultRequest\x1a1.internalaicopilot.integration.v1.ConsultResponse\x12\x83\x01\n" +
	"\x0eProfileConsult\x127.internalaicopilot.integration.v1.ProfileConsultRequest\x1a8.internalaicopilot.integration.v1.ProfileConsultResponse\x12\x86\x01\n" +
	"\x0fLineTaskConsult\x128.internalaicopilot.integration.v1.LineTaskConsultRequest\x1a9.internalaicopilot.integration.v1.LineTaskConsultResponseB3Z1linebot-backend/internal/internalclient/pb;grpcpbb\x06proto3"

var (
	file_api_grpc_internal_ai_proto_rawDescOnce sync.Once
	file_api_grpc_internal_ai_proto_rawDescData []byte
)

func file_api_grpc_internal_ai_proto_rawDescGZIP() []byte {
	file_api_grpc_internal_ai_proto_rawDescOnce.Do(func() {
		file_api_grpc_internal_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_internal_ai_proto_rawDesc), len(file_api_grpc_internal_ai_proto_rawDesc)))
	})
	return file_api_grpc_internal_ai_proto_rawDescData
}

var file_api_grpc_internal_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_grpc_internal_ai_proto_goTypes = []any{
	(*ListBuildersRequest)(nil),     // 0: internalaicopilot.integration.v1.ListBuildersRequest
	(*ListBuildersResponse)(nil),    // 1: internalaicopilot.integration.v1.ListBuildersResponse
	(*BuilderSummary)(nil),          // 2: internalaicopilot.integration.v1.BuilderSummary
	(*ConsultRequest)(nil),          // 3: internalaicopilot.integration.v1.ConsultRequest
	(*Attachment)(nil),              // 4: internalaicopilot.integration.v1.Attachment
	(*ConsultResponse)(nil),         // 5: internalaicopilot.integration.v1.ConsultResponse
	(*ProfileConsultRequest)(nil),   // 6: internalaicopilot.integration.v1.ProfileConsultRequest
	(*SubjectProfile)(nil),          // 7: internalaicopilot.integration.v1.SubjectProfile
	(*SubjectAnalysisPayload)(nil),  // 8: internalaicopilot.integration.v1.SubjectAnalysisPayload
	(*ProfileConsultResponse)(nil),  // 9: internalaicopilot.integration.v1.ProfileConsultResponse
	(*LineTaskConsultRequest)(nil),  // 10: internalaicopilot.integration.v1.LineTaskConsultRequest
	(*LineTaskConsultResponse)(nil), // 11: internalaicopilot.integration.v1.LineTaskConsultResponse
	(*FilePayload)(nil),             // 12: internalaicopilot.integration.v1.FilePayload
	(*structpb.Struct)(nil),         // 13: google.protobuf.Struct
}
var file_api_grpc_internal_ai_proto_depIdxs = []int32{
	2,  // 0: internalaicopilot.integration.v1.ListBuildersResponse.builders:type_name -> internalaicopilot.integration.v1.BuilderSummary
	4,  // 1: internalaicopilot.integration.v1.ConsultRequest.attachments:type_name -> internalaicopilot.integration.v1.Attachment
	12, // 2: internalaicopilot.integration.v1.ConsultResponse.file:type_name -> internalaicopilot.integration.v1.FilePayload
	7,  // 3: internalaicopilot.integration.v1.ProfileConsultRequest.subject_profile:type_name -> internalaicopilot.integration.v1.SubjectProfile
	8,  // 4: internalaicopilot.integration.v1.SubjectProfile.analysis_payloads:type_name -> internalaicopilot.integration.v1.SubjectAnalysisPayload
	13, // 5: internalaicopilot.integration.v1.SubjectAnalysisPayload.payload:type_name -> google.protobuf.Struct
	0,  // 6: internalaicopilot.integration.v1.IntegrationService.ListBuilders:input_type -> internalaicopilot.integration.v1.ListBuildersRequest
	3,  // 7: internalaicopilot.integration.v1.IntegrationService.Consult:input_type -> internalaicopilot.integration.v1.ConsultRequest
	6,  // 8: internalaicopilot.integration.v1.IntegrationService.ProfileConsult:input_type -> internalaicopilot.integration.v1.ProfileConsultRequest
	10, // 9: internalaicopilot.integration.v1.IntegrationService.LineTaskConsult:input_type -> internalaicopilot.integration.v1.LineTaskConsultRequest
	1,  // 10: internalaicopilot.integration.v1.IntegrationService.ListBuilders:output_type -> internalaicopilot.integration.v1.ListBuildersResponse
	5,  // 11: internalaicopilot.integration.v1.IntegrationService.Consult:output_type -> internalaicopilot.integration.v1.ConsultResponse
	9,  // 12: internalaicopilot.integration.v1.IntegrationService.ProfileConsult:output_type -> internalaicopilot.integration.v1.ProfileConsultResponse
	11, // 13: internalaicopilot.integration.v1.IntegrationService.LineTaskConsult:output_type -> internalaicopilot.integration.v1.LineTaskConsultResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_grpc_internal_ai_proto_init() }
func file_api_grpc_internal_ai_proto_init() {
	if File_api_grpc_internal_ai_proto != nil {
		return
	}
	file_api_grpc_internal_ai_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_grpc_internal_ai_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_internal_ai_proto_rawDesc), len(file_api_grpc_internal_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_internal_ai_proto_goTypes,
		DependencyIndexes: file_api_grpc_internal_ai_proto_depIdxs,
		MessageInfos:      file_api_grpc_internal_ai_proto_msgTypes,
	}.Build()
	File_api_grpc_internal_ai_proto = out.File
	file_api_grpc_internal_ai_proto_goTypes = nil
	file_api_grpc_internal_ai_proto_depIdxs = nil
}
